# File : .pep8speaks.yml

scanner:
    diff_only: True  # If True, errors caused by only the patch are shown

pycodestyle:
    max-line-length: 81
    ignore:  # Errors and warnings to ignore
        - E731
        - E402
    exclude:
        - to_exclude/
