message:
  opened:
    header: "Hello @{name}, Thank you for everything !"
    footer: "Bye bye!"
  updated:
  
    header: "Hello @{name}, Thank you for updating man!"
    footer: "Bye !"

ignore:
 - W391
 - E203

scanner:
    diff_only: True
